# Generated by Django 3.1.6 on 2021-02-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_cabeceracomandamodel_cbaeceraestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabeceracomandamodel',
            old_name='cbaeceraEstado',
            new_name='cabeceraEstado',
        ),
    ]
