# Generated by Django 3.1.6 on 2021-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomodel',
            name='inventarioCantidad',
            field=models.IntegerField(db_column='inventario_cantidad', default=None, verbose_name='Cantidad del plato'),
            preserve_default=False,
        ),
    ]
