# Generated by Django 3.1.4 on 2020-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoalmacenmodel',
            options={'verbose_name': 'Producto por almacen', 'verbose_name_plural': 'Productos por almacen'},
        ),
        migrations.AlterField(
            model_name='almacenmodel',
            name='almacenDescripcion',
            field=models.CharField(db_column='alma_desc', help_text='Aca va la descripcion del almacen', max_length=75, verbose_name='Descripcion del almacén'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoMinimo',
            field=models.IntegerField(db_column='prod_minimo', verbose_name='Cantidad minima del producto'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoNombre',
            field=models.CharField(db_column='prod_nom', max_length=45, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='productoPrecio',
            field=models.DecimalField(db_column='prod_prec', decimal_places=2, max_digits=5, verbose_name='Precio del producto'),
        ),
    ]
