# Generated by Django 3.1.4 on 2020-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20201212_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='productoEstado',
            field=models.BooleanField(db_column='prod_estado', default=True, verbose_name='Estado del producto'),
        ),
    ]
